### ISSUE TITLE
$.isPlainObject is not a function

### ISSUE THREAD

**Issue by hfloyd** [kswedberg/jquery-cluetip#66]
Though the requirements list jquery 1.3+ as the compatible version, I was not seeing the tooltips popup and was seeing these errors after hovering:

$.isPlainObject is not a function
success(data="\r\n", textStatus="success")
X = 9

if ( $.isPlainObject(cluetipContents) ) {

$.isPlainObject is not a function
data = "\r\n"
textStatus = "success"
X = 5

This was fixed when the page referenced "jquery-1.4.4.min.js" instead of 1.3.2.

Perhaps this newer version does require 1.4? 

(This page wasn't working: http://plugins.jquery.com/project/cluetip/ so I downloaded the current files from Github)

Thanks!

**Comment by ricardopinto08** [comment]
Review your framework version, I had the same problem with http requests with Vue and the problem was my vue-resource(package for http requests in vuew) version
Sorry, I'm a bit late. lol
